force-app/main/default/objects/Case/fields/Is_External__c.field-meta.xml
<CustomField>
    <fullName>Is_External__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is External</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Complaint_Approval_Request__c/Complaint_Approval_Request__c.object-meta.xml
<CustomObject>
    <label>Complaint Approval Request</label>
    <nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Complaint Approval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaint Approval Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Complaint_Approval_Request__c/fields/Amount_To_Refund__c.field-meta.xml
<CustomField>
    <fullName>Amount_To_Refund__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Amount To Refund</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Complaint_Approval_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Complaint Approval Requests</relationshipLabel>
    <relationshipName>Complaint_Approval_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Complaint_Approval_Request__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <label>External ID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Complaint_Approval_Request__c/fields/Is_External__c.field-meta.xml
<CustomField>
    <fullName>Is_External__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is External</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Complaint_Approval_Request__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Complaint Approval Requests</relationshipLabel>
    <relationshipName>Complaint_Approval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Complaint_Approval_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Waiting for response from external source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/complaintForm/SendToSecondOrgFlowAction.cls
public with sharing class SendToSecondOrgFlowAction {

    @InvocableMethod(label='Send Complaint to Second Org' description='Sends complaint approval request to second org')
    public static List<SendToSecondOrgResult> sendComplaintToSecondOrg(List<SendToSecondOrgRequest> requests) {
        List<SendToSecondOrgResult> results = new List<SendToSecondOrgResult>();

        for (SendToSecondOrgRequest request : requests) {
            SendToSecondOrgResult result = new SendToSecondOrgResult();
            try {
                Complaint_Approval_Request__c complaintRequest = [
                        SELECT Id, Case__c, Product__c, Status__c, Is_External__c, External_ID__c,
                                Product__r.Name, Product__r.ProductCode, Product__r.ExternalId,
                                Case__r.CaseNumber, Case__r.Order__c, Amount_To_Refund__c
                        FROM Complaint_Approval_Request__c
                        WHERE Id = :request.complaintApprovalRequestId
                        LIMIT 1
                ];

                sendUpdateCompositeTo2ndOrg(complaintRequest);
                result.isSuccess = true;

            } catch (Exception e) {
                result.isSuccess = false;
                result.message = System.Label.Error_sending_to_second_org + e.getMessage();
                throw new AuraHandledException(result.message);
            }
            results.add(result);
        }

        return results;
    }

    private static void sendUpdateCompositeTo2ndOrg(Complaint_Approval_Request__c complaintRequest) {
        String httpMethod = 'PATCH';
        String recordUrl = ConstUtil.ENDPOINT.SOBJECTS.COMPLAINT_APPROVAL_REQUEST__C + complaintRequest.External_ID__c;

        Map<String, Object> bodyMap = new Map<String, Object>{
                Complaint_Approval_Request__c.Status__c.toString() => complaintRequest.Status__c,
                Complaint_Approval_Request__c.Amount_To_Refund__c.toString() => complaintRequest.Amount_To_Refund__c
        };

        List<Complaint_CompositeRequestQueueable.CompositeSubRequest> subRequests =
                new List<Complaint_CompositeRequestQueueable.CompositeSubRequest>();

        subRequests.add(
                new Complaint_CompositeRequestQueueable.CompositeSubRequest(
                        httpMethod,
                        recordUrl,
                        complaintRequest.Id,
                        bodyMap
                )
        );
        System.enqueueJob(new Complaint_CompositeRequestQueueable(subRequests));
    }

    //Flow Properties
    public class SendToSecondOrgRequest {
        @InvocableVariable(label='Complaint Approval Request ID' required=true)
        public String complaintApprovalRequestId;
    }

    public class SendToSecondOrgResult {
        @InvocableVariable
        public Boolean isSuccess;

        @InvocableVariable
        public String message;
    }
}