force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Complaint_Approval_Request__c/Complaint_Approval_Request__c.object-meta.xml
<CustomObject>
    <label>Complaint Approval Request</label>
    <nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Complaint Approval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaint Approval Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Complaint_Approval_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Complaint Approval Requests</relationshipLabel>
    <relationshipName>Complaint_Approval_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Complaint_Approval_Request__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Complaint Approval Requests</relationshipLabel>
    <relationshipName>Complaint_Approval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Complaint_Approval_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Waiting for response from external source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/IsExternal__c.field-meta.xml
<CustomField>
    <fullName>IsExternal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is External</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/complaintForm/ComplaintFormService.cls
public with sharing class ComplaintFormService {
    public static List<OrderItem> getOrderItemsFromOrderId(Id orderId) {
        List<OrderItem> orderItems = [
                SELECT Id, OrderId, Quantity, Product2.ProductCode, Product2.Name, TotalPrice, Product2.IsExternal__c
                FROM OrderItem
                WHERE OrderId = :orderId
        ];
        System.debug(orderItems);
        return orderItems;
    }

    public static ComplaintSubmissionResult submitComplaintForApproval(List<Id> orderItemIds) {
        System.debug(orderItemIds);
        if (orderItemIds == null || orderItemIds.isEmpty()) {
            throw new AuraHandledException('You must select at least one product.');
        }

        List<OrderItem> itemsToProcess = [
                SELECT Id, OrderId, Product2.IsExternal__c, Product2.ExternalId
                FROM OrderItem
                WHERE Id IN :orderItemIds
        ];
        System.debug(itemsToProcess);

        List<Approval.ProcessSubmitRequest> internalApprovalRequests = new List<Approval.ProcessSubmitRequest>();
        List<Product2> externalComplaintEvents = new List<Product2>();

        Case caseForComplaint = new Case(
                Order__c = itemsToProcess[0].OrderId
        );
        insert caseForComplaint;
        System.debug(caseForComplaint);

        List<Complaint_Approval_Request__c> complaintApprovalRequests = new List<Complaint_Approval_Request__c>();

        for (OrderItem item : itemsToProcess) {
            if (item.Product2.IsExternal__c) {
                externalComplaintEvents.add(item.Product2);
            } else {
                Complaint_Approval_Request__c complaintApprovalRequest = new Complaint_Approval_Request__c();
                complaintApprovalRequest.Case__c = caseForComplaint.Id;
                complaintApprovalRequest.Status__c = 'Pending Approval';
                complaintApprovalRequest.Product__c = item.Product2Id;
                complaintApprovalRequests.add(complaintApprovalRequest);
            }
        }
        System.debug(complaintApprovalRequests);
        insert complaintApprovalRequests;

        for (Complaint_Approval_Request__c complaintApprovalRequest: complaintApprovalRequests) {
            Approval.ProcessSubmitRequest request = new Approval.ProcessSubmitRequest();
            request.setObjectId(complaintApprovalRequest.Id);
            request.setProcessDefinitionNameOrId('Approving_Complaint');
            internalApprovalRequests.add(request);
        }
        System.debug(internalApprovalRequests);
        try {
            if (!internalApprovalRequests.isEmpty()) {
                Approval.ProcessResult[] processResults = Approval.process(internalApprovalRequests, false);
                for (Approval.ProcessResult processResult : processResults) {
                    if (!processResult.success) {
                        throw new AuraHandledException('Error creating approval request: '+processResult.getErrors());
                    }
                }
                System.debug(processResults);
            }

            UUID randomUUID = UUID.randomUUID();
            if (!externalComplaintEvents.isEmpty()) {
                ExternalComplaintCallout.sendComplaintsAsync(externalComplaintEvents, randomUUID);
            }
            return new ComplaintSubmissionResult(caseForComplaint.Id, randomUUID?.toString());
        } catch (Exception e) {
            throw new AuraHandledException('Error processing complaint: ' + e.getMessage());
        }
    }
}