force-app/main/default/objects/Complaint_Approval_Request__c/Complaint_Approval_Request__c.object-meta.xml
<CustomObject>
    <label>Complaint Approval Request</label>
    <nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Complaint Approval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaint Approval Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Complaint_Approval_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Complaint Approval Requests</relationshipLabel>
    <relationshipName>Complaint_Approval_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Complaint_Approval_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Waiting for response from external source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Complaint_Approval_Status__e/External_Complaint_Approval_Status__e.object-meta.xml
<CustomObject>
    <label>External Complaint Approval Status</label>
    <pluralLabel>External Complaint Approval Statuses</pluralLabel>
</CustomObject>

force-app/main/default/objects/External_Complaint_Approval_Status__e/fields/External_Complaint_Request_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Complaint_Request_ID__c</fullName>
    <label>External Complaint Request ID</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Complaint_Approval_Status__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/complaintForm/triggers/tests/ExternalCAStatusEventTriggerTests.cls
@IsTest
public class ExternalCAStatusEventTriggerTests {
    @TestSetup
    static void setupTestData() {
        Case casea = new Case();
        insert casea;

        List<Complaint_Approval_Request__c> requestsToInsert = new List<Complaint_Approval_Request__c>();
        for (Integer i = 0; i < 5; i++) {
            requestsToInsert.add(new Complaint_Approval_Request__c(
                    Case__c = casea.Id
            ));
        }
        insert requestsToInsert;
    }

    @IsTest
    static void testSingleEventPublication() {
        Complaint_Approval_Request__c request = [
                SELECT Id, Status__c
                FROM Complaint_Approval_Request__c
                LIMIT 1
        ];

        Test.startTest();

        External_Complaint_Approval_Status__e event = new External_Complaint_Approval_Status__e(
                Status__c = 'SUCCESS',
                External_Complaint_Request_ID__c = request.Id
        );
        Database.SaveResult sr = EventBus.publish(event);
        Test.stopTest();

        System.assert(sr.isSuccess(), 'Publikacja zdarzenia powinna się powieść.');

        Complaint_Approval_Request__c updatedRequest = [
                SELECT Id, Status__c
                FROM Complaint_Approval_Request__c
                WHERE Id = :request.Id
        ];

        System.assertEquals(null, updatedRequest.Status__c);
    }

    @IsTest
    static void testBulkEventPublication() {
        List<Complaint_Approval_Request__c> requests = [
                SELECT Id, Status__c, Case__c
                FROM Complaint_Approval_Request__c
        ];

        List<External_Complaint_Approval_Status__e> eventsToPublish = new List<External_Complaint_Approval_Status__e>();
        for (Complaint_Approval_Request__c req : requests) {
            eventsToPublish.add(new External_Complaint_Approval_Status__e(
                    Status__c = 'APPROVED_BULK',
                    External_Complaint_Request_ID__c = req.Id
            ));
        }

        Test.startTest();
        List<Database.SaveResult> results = EventBus.publish(eventsToPublish);

        Test.stopTest();
        List<Complaint_Approval_Request__c> updatedRequests = [
                SELECT Id, Status__c
                FROM Complaint_Approval_Request__c
                WHERE Id IN :requests
        ];

        for (Complaint_Approval_Request__c updatedReq : updatedRequests) {
            System.assertEquals(null, updatedReq.Status__c);
        }
    }
}