force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Condition_Logic__c.field-meta.xml
<CustomField>
    <fullName>Condition_Logic__c</fullName>
    <label>Condition Logic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OrderItemsCondition</fullName>
                <label>Order Have Minimum 5 Items</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <description>Type of Discount</description>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recurring</fullName>
                <default>true</default>
                <label>Recurring</label>
            </value>
            <value>
                <fullName>Time-Bound</fullName>
            </value>
            <value>
                <fullName>Conditional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Value__c.field-meta.xml
<CustomField>
    <fullName>Discount_Value__c</fullName>
    <description>How much is discount value</description>
    <label>Discount Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Discount Active</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Recurring_Date_End__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Date_End__c</fullName>
    <label>Recurring Date End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Recurring_Date_Repeat_By__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Date_Repeat_By__c</fullName>
    <label>Recurring Date Repeat By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day of the Week</fullName>
            </value>
            <value>
                <fullName>Day of the Month</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Time of Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Recurring_Date_Start__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Date_Start__c</fullName>
    <label>Recurring Date Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Value_Type__c.field-meta.xml
<CustomField>
    <fullName>Value_Type__c</fullName>
    <description>How is Discount Applied by</description>
    <label>Value Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
                <default>true</default>
                <label>Percentage</label>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DiscountedAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountedAmount__c</fullName>
    <label>Discounted Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/discountCalculator/DiscountCalculatorHandler.cls
public with sharing class DiscountCalculatorHandler {

    //Triggered after insert to apply discounts
    public static void applyDiscountsWhenOrderTriggered(List<Order> orders) {
        DiscountSettings settings = new DiscountSettings();
        List<Discount__c> activeDiscounts = [
                SELECT Id, Name, Discount_Type__c, Value_Type__c, Discount_Value__c,
                        Start_Date__c, End_Date__c,
                        Condition_Logic__c,
                        Recurring_Date_Start__c, Recurring_Date_End__c, Recurring_Date_Repeat_By__c
                FROM Discount__c
                WHERE Is_Active__c = TRUE
        ];

        for (Order order : orders) {
            order.Discount__c = null;
        }

        for (Order currentOrder : orders) {
            List<Discount__c> filteredDiscounts = DiscountFilter.filterDiscounts(activeDiscounts, settings, currentOrder);
            if (filteredDiscounts.isEmpty()) {
                continue;
            }

            Decimal bestDiscountValue = 0;
            Discount__c bestDiscount = BestDiscountCounter.getMatchingDiscount(filteredDiscounts, settings, currentOrder);
            if (bestDiscount != null) {
                if (bestDiscount.Value_Type__c == ConstUtil.DISCOUNT.VALUE.TYPE.PERCENTAGE) {
                    bestDiscountValue = (currentOrder.TotalAmount * bestDiscount.Discount_Value__c / 100);
                } else if (bestDiscount.Value_Type__c == ConstUtil.DISCOUNT.VALUE.TYPE.FIXED_AMOUNT) {
                    bestDiscountValue = bestDiscount.Discount_Value__c;
                }

                currentOrder.Discount__c = bestDiscount.Id;
                currentOrder.DiscountedAmount__c = bestDiscountValue;
            }
        }
    }

    public static void applyDiscountsWhenDiscountTriggered() {
        List<Discount__c> activeDiscounts = [
                SELECT Id, Name, Discount_Type__c, Value_Type__c, Discount_Value__c,
                        Start_Date__c, End_Date__c,
                        Condition_Logic__c,
                        Recurring_Date_Start__c, Recurring_Date_End__c, Recurring_Date_Repeat_By__c,
                        Is_Active__c
                FROM Discount__c
                WHERE Is_Active__c = TRUE
        ];

        List<Order> ordersToProcess = [
                SELECT Id, TotalAmount, Discount__c, Status
                FROM Order
                WHERE Status = :ConstUtil.ORDER.STATUS.DRAFT
        ];

        DiscountSettings settings = new DiscountSettings();

        if (!ordersToProcess.isEmpty()) {
            for (Order order : ordersToProcess) {
                order.Discount__c = null;
            }

            for (Order currentOrder : ordersToProcess) {
                List<Discount__c> filteredDiscounts = DiscountFilter.filterDiscounts(activeDiscounts, settings, currentOrder);
                if (filteredDiscounts.isEmpty()) {
                    continue;
                }

                Decimal bestDiscountValue = 0;
                Discount__c bestDiscount = BestDiscountCounter.getMatchingDiscount(filteredDiscounts, settings, currentOrder);
                if (bestDiscount != null) {
                    if (bestDiscount.Value_Type__c == ConstUtil.DISCOUNT.VALUE.TYPE.PERCENTAGE) {
                        bestDiscountValue = (currentOrder.TotalAmount * bestDiscount.Discount_Value__c / 100);
                    } else if (bestDiscount.Value_Type__c == ConstUtil.DISCOUNT.VALUE.TYPE.FIXED_AMOUNT) {
                        bestDiscountValue = bestDiscount.Discount_Value__c;
                    }

                    currentOrder.Discount__c = bestDiscount.Id;
                    currentOrder.DiscountedAmount__c = bestDiscountValue;
                }
            }
            update ordersToProcess;
        }
    }
}