force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Condition_Logic__c.field-meta.xml
<CustomField>
    <fullName>Condition_Logic__c</fullName>
    <label>Condition Logic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OrderItemsCondition</fullName>
                <label>Order Have Minimum 5 Items</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/discountCalculator/ConditionLogicValidator.cls
public with sharing class ConditionLogicValidator {
    public static Boolean filterDiscountsByConditionLogic(Discount__c discount, Order order) {
        String selectedApiName = discount.Condition_Logic__c;

        ICondition condition;
        try {
            Type conditionType = Type.forName(selectedApiName);

            Object conditionInstance = conditionType.newInstance();
            condition = (ICondition) conditionInstance;
        } catch (Exception e) {
            return false;
        }

        if (condition == null) {
            return false;
        }

        return condition.isApplicable(order);
    }
}