force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Discount_Value__c.field-meta.xml
<CustomField>
    <fullName>Discount_Value__c</fullName>
    <description>How much is discount value</description>
    <label>Discount Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Value_Type__c.field-meta.xml
<CustomField>
    <fullName>Value_Type__c</fullName>
    <description>How is Discount Applied by</description>
    <label>Value Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
                <default>true</default>
                <label>Percentage</label>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/discountCalculator/BestDiscountCounter.cls
public with sharing class BestDiscountCounter {
    public static Discount__c getMatchingDiscount(List<Discount__c> discounts, DiscountSettings settings, Order currentOrder) {
        Decimal bestDiscountValue = 0;
        Discount__c bestDiscount = null;

        for (Discount__c discount : discounts) {
            Decimal discountValue = 0;
            if (discount.Value_Type__c == 'Percentage') {
                discountValue = currentOrder.TotalAmount * discount.Discount_Value__c / 100;
            } else if (discount.Value_Type__c == 'Fixed Amount') {
                discountValue = discount.Discount_Value__c;
            }

            if (settings.strategy == 'Highest' && discountValue > bestDiscountValue) {
                bestDiscountValue = discountValue;
                bestDiscount = discount;
            } else if (settings.strategy == 'Lowest' && (bestDiscount == null || discountValue < bestDiscountValue)) {
                bestDiscountValue = discountValue;
                bestDiscount = discount;
            }
        }

        return bestDiscount;
    }

    public static Discount__c getMatchingDiscountBasedOnTotalAmount(List<Discount__c> discounts, DiscountSettings settings, Decimal totalAmount) {
        Decimal bestDiscountValue = 0;
        Discount__c bestDiscount = null;

        for (Discount__c discount : discounts) {
            Decimal discountValue = 0;
            if (discount.Value_Type__c == 'Percentage') {
                discountValue = totalAmount * discount.Discount_Value__c / 100;
            } else if (discount.Value_Type__c == 'Fixed Amount') {
                discountValue = discount.Discount_Value__c;
            }

            if (settings.strategy == 'Highest' && discountValue > bestDiscountValue) {
                bestDiscountValue = discountValue;
                bestDiscount = discount;
            } else if (settings.strategy == 'Lowest' && (bestDiscount == null || discountValue < bestDiscountValue)) {
                bestDiscountValue = discountValue;
                bestDiscount = discount;
            }
        }

        return bestDiscount;
    }
}