force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/discountCalculator/TimeBoundValidator.cls
public with sharing class TimeBoundValidator {
    public static Boolean isValidTimeBoundDiscount(Discount__c discount) {
        if (discount.Start_Date__c == null || discount.End_Date__c == null) {
            return false;
        }

        Datetime startDate = Datetime.newInstance(discount.Start_Date__c, Time.newInstance(0, 0, 0, 0));
        Datetime endDate = Datetime.newInstance(discount.End_Date__c, Time.newInstance(0, 0, 0, 0));

        if (startDate >= endDate) {
            return false;
        }

        if (Datetime.now() >= startDate && Datetime.now() <= endDate) {
            return true;
        }
        return false;
    }
}