force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <description>Type of Discount</description>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recurring</fullName>
                <default>true</default>
                <label>Recurring</label>
            </value>
            <value>
                <fullName>Time-Bound</fullName>
            </value>
            <value>
                <fullName>Conditional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/discountCalculator/DiscountFilter.cls
public with sharing class DiscountFilter {
    public static List<Discount__c> filterDiscounts(List<Discount__c> discounts, DiscountSettings settings, Order order) {
        List<Discount__c> filteredDiscounts = new List<Discount__c>();

        for (Discount__c discount : discounts) {
            System.debug('Evaluating Discount: ' + discount.Name + ' of type ' + discount.Discount_Type__c);
            switch on discount.Discount_Type__c {
                //From date to date
                when 'Time-Bound' {
                    if (TimeBoundValidator.isValidTimeBoundDiscount(discount)) {
                        filteredDiscounts.add(discount);
                    }
                }
                //Cron activated
                when 'Recurring' {
                    if (RecurringDateValidator.isRecurringDateValidForToday(discount)) {
                        filteredDiscounts.add(discount);
                    }
                }
                //Only if order is eligible
                when 'Conditional' {
                    order = [SELECT Id, TotalAmount, (SELECT Id, UnitPrice, Quantity FROM OrderItems) FROM Order WHERE Id = :order.Id];
                    if (ConditionLogicValidator.filterDiscountsByConditionLogic(discount, order)) {
                        filteredDiscounts.add(discount);
                    }
                }
            }
        }

        return filteredDiscounts;
    }
}