force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Condition_Logic__c.field-meta.xml
<CustomField>
    <fullName>Condition_Logic__c</fullName>
    <label>Condition Logic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OrderItemsCondition</fullName>
                <label>Order Have Minimum 5 Items</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <description>Type of Discount</description>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recurring</fullName>
                <default>true</default>
                <label>Recurring</label>
            </value>
            <value>
                <fullName>Time-Bound</fullName>
            </value>
            <value>
                <fullName>Conditional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Value__c.field-meta.xml
<CustomField>
    <fullName>Discount_Value__c</fullName>
    <description>How much is discount value</description>
    <label>Discount Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Discount Active</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Recurring_Date_End__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Date_End__c</fullName>
    <label>Recurring Date End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Recurring_Date_Repeat_By__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Date_Repeat_By__c</fullName>
    <label>Recurring Date Repeat By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day of the Week</fullName>
            </value>
            <value>
                <fullName>Day of the Month</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Time of Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Recurring_Date_Start__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Date_Start__c</fullName>
    <label>Recurring Date Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Value_Type__c.field-meta.xml
<CustomField>
    <fullName>Value_Type__c</fullName>
    <description>How is Discount Applied by</description>
    <label>Value Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
                <default>true</default>
                <label>Percentage</label>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/builders/DiscountBuilder.cls
public class DiscountBuilder {
    private Discount__c discount;

    private DiscountBuilder() {
        this.discount = new Discount__c();
    }

    public static DiscountBuilder create() {
        return new DiscountBuilder();
    }

    public DiscountBuilder withName(String name) {
        this.discount.Name = name;
        return this;
    }

    public DiscountBuilder withDiscountType(String discountType) {
        this.discount.Discount_Type__c = discountType;
        return this;
    }

    public DiscountBuilder withValueType(String valueType) {
        this.discount.Value_Type__c = valueType;
        return this;
    }

    public DiscountBuilder withDiscountValue(Decimal discountValue) {
        this.discount.Discount_Value__c = discountValue;
        return this;
    }

    public DiscountBuilder withStartDate(Date startDate) {
        this.discount.Start_Date__c = startDate;
        return this;
    }

    public DiscountBuilder withEndDate(Date endDate) {
        this.discount.End_Date__c = endDate;
        return this;
    }

    public DiscountBuilder withIsActive(Boolean isActive) {
        this.discount.Is_Active__c = isActive;
        return this;
    }

    public DiscountBuilder withConditionLogic(String field) {
        this.discount.Condition_Logic__c = field;
        return this;
    }

    public DiscountBuilder withRecurringDateStart(Datetime recurringDateStart) {
        this.discount.Recurring_Date_Start__c = recurringDateStart;
        return this;
    }

    public DiscountBuilder withRecurringDateEnd(Datetime recurringDateEnd) {
        this.discount.Recurring_Date_End__c = recurringDateEnd;
        return this;
    }

    public DiscountBuilder withRecurringDateRepeatBy(String repeatBy) {
        this.discount.Recurring_Date_Repeat_By__c = repeatBy;
        return this;
    }

    public Discount__c build() {
        return this.discount;
    }
}