force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <description>Type of Discount</description>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recurring</fullName>
                <default>true</default>
                <label>Recurring</label>
            </value>
            <value>
                <fullName>Time-Bound</fullName>
            </value>
            <value>
                <fullName>Conditional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Value__c.field-meta.xml
<CustomField>
    <fullName>Discount_Value__c</fullName>
    <description>How much is discount value</description>
    <label>Discount Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Discount Active</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Value_Type__c.field-meta.xml
<CustomField>
    <fullName>Value_Type__c</fullName>
    <description>How is Discount Applied by</description>
    <label>Value Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
                <default>true</default>
                <label>Percentage</label>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/discountCalculator/tests/DiscountFilterTests.cls
@IsTest
private class DiscountFilterTests {
    @TestSetup
    static void setup() {
        List<Discount__c> discounts = new List<Discount__c>();
        Discount__c discount1 = (Discount__c) new DiscountTestDataFactory().create();
        discounts.add(discount1);
        Discount__c expiredDiscount = (Discount__c) new ExpiredDiscountDataFactory().create();
        discounts.add(expiredDiscount);
        insert discounts;
    }

    @IsTest
    static void testCalculateDiscounterAmount(){
        DiscountSettings settings = new DiscountSettings();
        List<Discount__c> discounts = [SELECT Id, Name, Value_Type__c, Discount_Value__c, Start_Date__c, End_Date__c, Discount_Type__c FROM Discount__c WHERE Is_Active__c = TRUE];
        Decimal totalAmount = 1000.0;
        Test.startTest();
        Decimal discountedAmount = DiscountFilter.calculateDiscountedAmount(discounts, settings, totalAmount);
        Test.stopTest();

        System.assertEquals(900.0, discountedAmount, 'Discounted amount should be 900.0 based on the active discount');
    }

    private class ExpiredDiscountDataFactory extends DiscountTestDataFactory {
        public override SObject create() {
            Discount__c discount = (Discount__c) super.create();
            discount.Name = 'Expired Discount';
            discount.Start_Date__c = Date.today().addDays(-10);
            discount.End_Date__c = Date.today().addDays(-5);
            return discount;
        }
    }
}