force-app/main/default/objects/Product_Synchronization_Log__c/Product_Synchronization_Log__c.object-meta.xml
<CustomObject>
    <label>Product Synchronization Log</label>
    <nameField>
        <displayFormat>PROD-SYNC-{0000}</displayFormat>
        <label>Product Synchronization Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Synchronization Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Synchronization_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product_Synchronization_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product_Synchronization_Log__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Retry Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Synchronization_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>RESOLVED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Synchronization_Log__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/builders/ProductSynchronizationLogBuilder.cls
public class ProductSynchronizationLogBuilder {
    private Product_Synchronization_Log__c log;

    private ProductSynchronizationLogBuilder() {
        this.log = new Product_Synchronization_Log__c();
        this.log.Retry_Count__c = 0;
    }

    public static ProductSynchronizationLogBuilder create() {
        return new ProductSynchronizationLogBuilder();
    }

    public ProductSynchronizationLogBuilder withId(Id id) {
        this.log.Id = id;
        return this;
    }
    public ProductSynchronizationLogBuilder withRequestBody(String requestBody) {
        this.log.request_Body__c = requestBody;
        return this;
    }
    public ProductSynchronizationLogBuilder withResponseBody(String responseBody) {
        this.log.response_Body__c = responseBody;
        return this;
    }
    public ProductSynchronizationLogBuilder withStatus(LogStatus status) {
        this.log.Status__c = status.toString();
        return this;
    }

    public ProductSynchronizationLogBuilder withTime(DateTime timeOfLog) {
        this.log.Time__c = timeOfLog;
        return this;
    }

    public Product_Synchronization_Log__c build() {
        if (this.log.Time__c == null) {
            this.log.Time__c = System.now();
        }
        if (this.log.Status__c == null) {
            this.log.Status__c = LogStatus.SUCCESS.toString();
        }
        return this.log;
    }

    public enum LogStatus {
        SUCCESS,
        ERROR,
        RESOLVED,
        FAILED
    }

    public ProductSynchronizationLogBuilder withRetryCount(Integer retryCount) {
        this.log.Retry_Count__c = retryCount;
        return this;
    }
}